apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: my-database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql-data

